### ISSUE TITLE
Silently fails ROM export when file is in use by another program.

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/CTRMap-CE#7]
I noticed for some reason, when exporting a ROM, the ROM itself didn't actually get updated at all. Upon opening up CTRMap using the command line, I saw that it choked on a file being in use, but this is no longer relayed outside of the console and isn't put into a log file either. In past versions of CTRMap, these errors would appear to the end user rather than showing no error dialog like the present behavior.

Steps of replication:
1. Have a vfs file locked by it being used in another program
2. Export a ROM from CTRMap

**Comment by HelloOO7** [comment]
> In past versions

Assuming this is a regression then. Are you able to pinpoint a commit # in which the behavior is as you'd expect?

**Comment by BromBromBromley** [comment]
With the earliest CE and Gen V plugin pairing I have, the one for Sept. 28, 2022 (commit 6507b51c71774f582c24c6072d8372f92538b134 seemingly) it similarly only reports back to the command line the error in question. It seems the severity is null according to the log made in the console. Here's the actual thing shown in the console:

```Aug 22, 2023 4:46:19 PM xstandard.fs.FSUtil readFileToBytes
SEVERE: null
java.nio.file.FileSystemException: C:\Users\<NAME>\Desktop\Recreational\Projects\Vegasoft Projects\sf\vfs\data\a\0\7\2\15: The process cannot access the file because it is being used by another process
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at xstandard.fs.FSUtil.readFileToBytes(FSUtil.java:377)
        at xstandard.fs.FSUtil.readFileToBytes(FSUtil.java:400)
        at ctrmap.formats.ntr.narc.DirectNARC.insertEntries(DirectNARC.java:306)
        at ctrmap.formats.ntr.narc.DirectNARC.setData(DirectNARC.java:246)
        at WSFSPlugin.writeToArcFile(WSFSPlugin.java:56)
        at ctrmap.editor.system.workspace.WSFS.writeToArcFile(WSFS.java:182)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:105)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.lambda$registUI$0(CTRMapPlugin.java:139)
        at ctrmap.editor.CTRMapUIManager$1.actionPerformed(CTRMapUIManager.java:35)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:983)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
        at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:710)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:717)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:717)
        at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:688)
        at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
        at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
        at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:3040)
        at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3032)
        at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
        at java.desktop/java.awt.Component.processEvent(Component.java:6403)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read the array length because "b" is null
        at xstandard.io.base.impl.ext.data.DataIOStream.write(DataIOStream.java:187)
        at ctrmap.formats.ntr.narc.DirectNARC.insertEntries(DirectNARC.java:306)
        at ctrmap.formats.ntr.narc.DirectNARC.setData(DirectNARC.java:246)
        at WSFSPlugin.writeToArcFile(WSFSPlugin.java:56)
        at ctrmap.editor.system.workspace.WSFS.writeToArcFile(WSFS.java:182)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:105)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.loadVFS(CTRMapPlugin.java:111)
        at CTRMapPlugin.lambda$registUI$0(CTRMapPlugin.java:139)
        at ctrmap.editor.CTRMapUIManager$1.actionPerformed(CTRMapUIManager.java:35)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:983)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
        at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:710)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:717)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:717)
        at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:688)
        at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
        at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
        at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:3040)
        at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3032)
        at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
        at java.desktop/java.awt.Component.processEvent(Component.java:6403)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)```

After this happens, CTRMap continues to run as if nothing happened with the UI responding to events like hovering over buttons and the like.

**Comment by HelloOO7** [comment]
Right, do I take it that this is not a regression then?
I would expect the errors to be silent since they have been like that in the file copy backend for as long as I can remember. Not that it's the most user-friendly behavior, but it is one I am reluctant to change, since it would most certainly break a lot of things that depend on it.

**Comment by BromBromBromley** [comment]
I think it technically is a regression since the pre-CE versions showed this to the end user, but I also am aware that there was a major change in VFS behavior between the two as well. It's fair not directly showing it through an error message, but maybe exporting to a log when an error occurs would be good? But I'm uncertain if that'd also be difficult too...

**Comment by HelloOO7** [comment]
Unfortunately, I do not have VCd sources of pre-CE releases.
The behavior was mostly unchanged, however, the ROM exporter was rewritten (I recall that was in a later CE though?) to use the VFS directly instead of requiring to commit the changes to the original filesystem. Technically, the later error message (NullPointerException), which is caused by the return value of the prior one, can be caught and displayed, however, on its own it is rather uninformative.

As for error logging, that is kind of meant to happen in log/StdOut.log, however, due to the bloated Java PrintStream architecture (two separate methods for every primitive type, from days where auto-boxing wasn't a thing), I wasn't very keen on writing a multi-stream sink for the error output, so enabling it does redirect it to a file, but also disables it in console, which is far from ideal, hence why it has been disabled pretty much since the beginning of time.

Both of those are very old deficiencies whose fixes are long overdue, and they arent particularly difficult to resolve, it's just that I'm not really interested enough anymore to pursue any significant changes. I'll leave this open for if I want to do something about it later.

**Comment by BromBromBromley** [comment]
Ah, I see. Thanks for the consideration regardless!
